# Generated by Django 4.0.6 on 2023-02-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_result_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='choices',
        ),
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(default='opt1', max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(default='opt2', max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(default='opt3', max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(default='opt4', max_length=100),
        ),
    ]
